<?php
declare(strict_types=1);
require_once __DIR__ . '/../../includes/bootstrap.php';
Auth::requireRole(['Dean']);

use Dompdf\Dompdf;
use Dompdf\Options;

$db = Database::connection();
$currentUser = Auth::user();
$filters = scoped_report_filters($_GET, $currentUser);
$rows = build_attendance_report_rows($db, $filters);

$totalRows = count($rows);
$present = count(array_filter($rows, function ($r) {
    return $r['attendance_status'] === 'Present';
}));
$rate = $totalRows ? round($present / $totalRows * 100) : 0;

ob_start();
?>
<html>
<head>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1B1F2A; }
  h1 { font-size: 16px; color: #1E2A52; margin-bottom: 2px; }
  .meta { color: #6B7280; font-size: 10px; margin-bottom: 14px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th { background: #1E2A52; color: #fff; text-align: left; padding: 6px 8px; font-size: 10px; }
  td { padding: 6px 8px; border-bottom: 1px solid #E4E7EF; font-size: 10px; }
  .summary td { background: #F6F7FB; text-align: center; font-weight: bold; font-size: 13px; }
  .present { color: #2F9E68; font-weight: bold; }
  .absent { color: #E2554B; font-weight: bold; }
</style>
</head>
<body>
  <h1>UNIVERSITY OF KIGALI &mdash; Attendance &amp; Compliance Report</h1>
  <div class="meta">
    Student Event Management &amp; Announcement System (SEMAS)<br>
    Generated by: <?= htmlspecialchars($currentUser['full_name']) ?> (<?= htmlspecialchars(Auth::role()) ?>) on <?= date('Y-m-d H:i') ?>
  </div>
  <table class="summary"><tr>
    <td><?= $totalRows ?><br><span style="font-size:9px;font-weight:normal;">Registrations</span></td>
    <td><?= $present ?><br><span style="font-size:9px;font-weight:normal;">Present</span></td>
    <td><?= $totalRows - $present ?><br><span style="font-size:9px;font-weight:normal;">Absent</span></td>
    <td><?= $rate ?>%<br><span style="font-size:9px;font-weight:normal;">Attendance Rate</span></td>
  </tr></table>
  <table>
    <tr>
      <th>Event</th><th>Venue</th><th>Date</th><th>Reg. Number</th><th>Full Name</th>
      <th>Department</th><th>Phone</th><th>Email</th><th>Check-in Time</th><th>Status</th>
    </tr>
    <?php foreach ($rows as $r): ?>
      <tr>
        <td><?= htmlspecialchars($r['event_title']) ?></td>
        <td><?= htmlspecialchars($r['venue']) ?></td>
        <td><?= htmlspecialchars($r['event_date']) ?></td>
        <td><?= htmlspecialchars($r['reg_number'] ?? '') ?></td>
        <td><?= htmlspecialchars($r['full_name']) ?></td>
        <td><?= htmlspecialchars($r['department_name'] ?? '') ?></td>
        <td><?= htmlspecialchars($r['phone_number'] ?? '') ?></td>
        <td><?= htmlspecialchars($r['email']) ?></td>
        <td><?= htmlspecialchars($r['checkin_time'] ?? '') ?></td>
        <td class="<?= $r['attendance_status'] === 'Present' ? 'present' : 'absent' ?>"><?= htmlspecialchars($r['attendance_status']) ?></td>
      </tr>
    <?php endforeach; ?>
  </table>
</body>
</html>
<?php
$html = ob_get_clean();

$options = new Options();
$options->set('isRemoteEnabled', false);
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

AuditLog::record(Auth::id(), 'EXPORT_PDF_REPORT', null, null, json_encode($filters));

$dompdf->stream('semas-attendance-report-' . date('Ymd-His') . '.pdf', ['Attachment' => true]);
